### ISSUE TITLE
Persistência de dados

### ISSUE THREAD

**Issue by JFSF** [armandocorrea/sonarqube-delphi-docker#2]
Dado que uma imagem docker quando "desligada" não persiste obrigatoriamente os dados nela utilizados, depois da instalação do sonarqube convém executar os seguintes comandos para o efeito:

**_docker volume create --name sonarqube_data
docker volume create --name sonarqube_logs
docker volume create --name sonarqube_extensions_**

Por fim podemos executar o sonarqube através do seguinte comando:

**_docker run -d --name sonarqube \
    -p 9000:9000 \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    <image_name>_**

**Comment by armandocorrea** [comment]
Obrigado pela contribuição. Ajustei a documentação.

No docker-compose ele já cria os volumes. Porém ajustei a doc para quem quiser rodar sem o compose.
